export const routes = [
  {
    path:'/',
    component:()=>import('../views/Home.vue'),
    redirect:'/home',
    meta:{title:'主页',icon:''}
  },
  {
    name:'Home',
    path:'/home',
    redirect:'/home/homepage',
    component:()=>import('../layout/homeLayout.vue'),
    meta:{title:'主页',icon:''},
    children:[
      {
        name:'homepage',
        path:'/home/homepage',
        component:()=>import('../views/Home.vue'),
        meta:{title:'主页',icon:''}
      }
    ]
  },
  {
    name:'Category',
    path:'/category/:url',
    component:()=>import('../views/Category.vue'),
    meta:{title:'详情',icon:''}
  }
]